accounts/urls.py
from django.urls import path
from .views import (
    register_view,
    login_view,
    logout_view,
    user_profile,
    calculate_disease,
    view_disease,
    view_dashboard
)
urlpatterns = [
    path("profile/", user_profile, name="profile"),
    path("register/", register_view, name="register"),
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("disease/", calculate_disease, name="disease"),
    path("disease/show", view_disease, name="disease_show"),
    path("statistics/show", view_dashboard, name="statistics"),
]

hdps/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import home_page
urlpatterns = [
    path("", home_page, name="home"),
    path('admin/', admin.site.urls),
    path('users/', include(("accounts.urls", "accounts"), namespace='accounts')),
]

templates/base/css.html
{% load static %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css"
    integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.css">

<!-- Custom css -->
<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'css/fontawesome.css' %}">
<!-- custom styleshee  -->
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<!-- custom styleshee  -->
<link rel="stylesheet" href="{% static 'css/base.css' %}">
<link rel="stylesheet" href="{% static 'css/stylesCopy.css' %}">

templates/base/forms.html
{% extends "base.html" %}


{% block content %}
<div class='col-12 col-md-6 mx-auto'>
{% if title %}<h1 class='my-3'>{{ title }}</h1>{% endif %}
<form method='POST' action='{% if action_url %}{{ action_url }}{% endif %}'> {% csrf_token %}
    {% if next_url %}
    <input type='hidden' name='next' value='{{ next_url }}' />
    {% endif %}
  {{ form.as_p }}
  <button type='submit' class='btn btn-default'>Save</button>
</form>
</div>
{% endblock %}

templates/base/js.html
{% load static %}
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS
slim is missing ajax -->
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

<!-- Stripe JS -->
<script src="https://js.stripe.com/v3/"></script>


<!-- jquery-confirm JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.js"></script>

<!-- js Render -->
<script src='https://cdnjs.cloudflare.com/ajax/libs/jsrender/0.9.88/jsrender.min.js'></script>
{% include 'base/js_templates.html' %}


<!-- Chart.js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js"></script>

<!-- Custom js -->
<script src='{% static "js/bootstrap.js" %}'></script>
<script src='{% static "js/custom.js" %}'></script>
<script src='{% static "js/jquery-3.4.0.min.js" %}'></script>
<script src='{% static "js/popper.min.js" %}'></script>



<!-- Latest compiled and minified JavaScript -->
<script src="http://code.jquery.com/jquery-1.12.2.min.js" integrity="sha256-lZFHibXzMHo3GGeehn1hudTAP3Sc0uKXBXAzHX1sjtk=" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.5/marked.min.js'></script>

templates/base/js_templates.html
{% verbatim %}
<!-- stripe template form -->
<script id="stripeTemplate" type="text/x-jsrender">
    <form class='payment-form' action="" method="post" id="payment-form" data-token='{{:publishKey}}' data-next-url='{{:nextUrl}}'>
  <div class="form-row">
    <!-- <label for="card-element">
      Credit or debit card
    </label> -->
    <div id="card-element" class='form-control'> 
      <!-- a Stripe Element will be inserted here. -->
    </div>

    <!-- Used to display form errors -->
    <div id="card-errors" role="alert"></div>
  </div>

  <button class='btn btn-primary my-3 btn-load'>{{:btnTitle }}</button>

    </form>

</script>
{% endverbatim %}

templates/base/navbar.html

{% url 'accounts:login' as login_url %}
{% url 'accounts:logout' as logout_url %}
{% url 'accounts:register' as register_url %}
{% url 'accounts:profile' as user_profile %}
{% url 'accounts:disease' as disease_url %}
{% url 'accounts:disease_show' as disease_show_url %}

<section id="navigation" class="bg-dark fixed-top">
  <nav class="navbar navbar-expand-md navbar-dark scrolling-navbar">
    <a href="{% url 'home' %}" class="navbar-brand" style="font-weight: bold;">HDPS</a>
    <div class="collapse navbar-collapse font-weight-bold" id="navbarCollapse">

      <ul class="navbar-nav ml-auto">
        <!-- Help End -->
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a href="{{ disease_url }}" class="nav-link">Check Diseases</a>
        </li>
        <li class="nav-item">
          <a href="{{ disease_show_url }}" class="nav-link">Disease Status</a>
        </li>
        <li class="nav-item">
          <a href="{{ user_profile }}" class="nav-link">{{user}}</a>
        </li>
        <li class="nav-item">
          <a href="{{ logout_url }}" class="nav-link">Logout</a>
        </li>
        {% else %}
        <!-- <li class="nav-item">
          <a href="{{ register_url }}" class="nav-link">Sign Up</a>
        </li>
        <li class="nav-item">
          <a href="{{ login_url }}" class="nav-link">Sign in</a>
        </li> -->
        {% endif %}
      </ul>
    </div>
  </nav>
</section>